FROM python:3.7.4-slim-buster AS py
ARG VERSION=2.3.0
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir \
        tensorflow==$VERSION

FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04 AS lib
ARG LIBNVINFER=6.0.1-1
ARG LIBNVINFER_MAJOR_VERSION=6
RUN apt-get update && apt-get install -y --no-install-recommends \
        libnvinfer${LIBNVINFER_MAJOR_VERSION}=${LIBNVINFER}+cuda10.1 \
        libnvinfer-plugin${LIBNVINFER_MAJOR_VERSION}=${LIBNVINFER}+cuda10.1 \
        libhdf5-serial-dev \
        libzmq3-dev && \
    rm -rf /var/lib/apt/lists/*

# Python version 3.7.3
FROM gcr.io/distroless/python3-debian10

# Python packages
COPY --from=py /usr/local/lib/python3.7/site-packages /site-packages

# CUDA libraries
COPY --from=lib /usr/local/cuda/compat /usr/local/cuda/compat
COPY --from=lib \
    /usr/lib/x86_64-linux-gnu/libnvinfer.so.6 \
    /usr/lib/x86_64-linux-gnu/libnvinfer_plugin.so.6 \
    /usr/lib/x86_64-linux-gnu/

# system libraries
COPY --from=lib \
    /usr/include/hdf5 \
    /usr/include/zmq.h \
    /usr/include/zmq.hpp \
    /usr/include/zmq_utils.h \
    /usr/include/
COPY --from=lib \
    /usr/lib/x86_64-linux-gnu/hdf5 \
    /usr/lib/x86_64-linux-gnu/libhdf5* \
    /usr/lib/x86_64-linux-gnu/pkgconfig/hdf5-serial.pc \
    /usr/lib/x86_64-linux-gnu/libzmq.a \
    /usr/lib/x86_64-linux-gnu/libzmq.so \
    /usr/lib/x86_64-linux-gnu/pkgconfig/libzmq.pc \
    /usr/lib/x86_64-linux-gnu/

ENV PYTHONPATH=/site-packages
ENV LD_LIBRARY_PATH=/apps/software/standard/core/cudnn/7.6.5.32/lib64:/apps/software/standard/core/cuda/10.1.168/nvvm/lib64:/apps/software/standard/core/cuda/10.1.168/extras/CUPTI/lib64:/apps/software/standard/core/cuda/10.1.168/lib64:/usr/lib/x86_64-linux-gnu
ENV LANG C.UTF-8

LABEL maintainer=rs7wz@virginia.edu

ENTRYPOINT ["/usr/bin/python"]
