#!/bin/bash
README="README.md"
LIST="List of Docker images" 

TMP=$(mktemp)

function get_image_info {
    if [ $# -ne 2 ]; then
        echo "get_image_info app version"
        exit 1
    fi
    curl -slSL https://hub.docker.com/v2/repositories/uvarc/$1/tags/$2 | tr ',' '\n' >$TMP
}

cat >$README <<EOF
# rivanna-docker

**Autogenerated - do not edit manually!**  
Run \`writeREADME.sh\` to update this \`README.md\`.

This repository contains Dockerfiles for Rivanna.

## Structure

<pre>
.
├── app1
│   ├── version1
│   │   ├── Dockerfile
│   │   └── README.md
│   └── version2
│       ├── Dockerfile
│       └── README.md
├── app2
│   └── version1
│       ├── Dockerfile
│       └── README.md
├── README.md  # Do not edit this file!
└── writeREADME.sh
</pre>

Each Dockerfile should reside in its own directory with a \`README.md\` with this template:
\`\`\`\`
<name of main app> <version> <any other important info>

<homepage of main app>

<any other apps/packages>

Usage on Rivanna:
\`\`\`
module load singularity
singularity pull docker://uvarc/<app>:<tag>
./<app>_<tag>.sif
\`\`\`
\`\`\`\`

Individual \`README.md\` files are used as the Docker Hub repository description.

## Instructions for Contribution

1. Install the following utilities if not on our machine:
    * \`docker\`
    * \`docker-pushrm\` - add-on to push \`README.md\`  
    https://github.com/christian-korneck/docker-pushrm
    * \`git\`
1. Clone this repository
1. Build and test
    1. Prepare a \`Dockerfile\`
    1. Build with explicit tag (do not use \`latest\`): \`docker build -t uvarc/<app>:<tag>\`  
       Use the app version (and suffix if needed) as the tag
    1. Test locally (or on Rivanna - see below)
1. Write \`README.md\` for the app
1. Deploy
    1. Login to Docker Hub: \`docker login\`
    1. Push image to Docker Hub: \`docker push uvarc/<app>:<tag>\`
    1. Push \`README.md\` to Docker Hub (in subdirectory): \`docker pushrm uvarc/<app>\`
    1. Push to GitHub: \`git add . && git commit -m "your message" && git push\`
    1. Remember to logout: \`docker logout\`
1. Run on Rivanna
    1. \`module load singularity\`
    1. \`singularity pull docker://uvarc/<app>:<tag>\`
    1. To run the default command specified in \`ENTRYPOINT\`:  
       \`./<app>_<tag>.sif\`  
       Otherwise:  
       \`singularity exec <app>_<tag>.sif <command>\` or  
       \`singularity shell <app>_<tag>.sif\`

## $LIST

|App|Version|Base Image|Compressed Size|Last Updated (UTC)|By|
|---|---|----|---:|---|---|
EOF

for i in *;  do
    if [ -d $i ]; then
        cd $i
        for j in *; do
            if [ -e $j/Dockerfile ]; then
                get_image_info $i $j

                # base image
                base=$(awk '{if(NR==1) print $2}' $j/Dockerfile)

                # size in MB
                size=$(awk -F':' '/full_size/ {
                    if ($2>=1e9) printf "%.3f GB", $2/1024/1024/1024
                    else         printf "%.3f MB", $2/1024/1024
                }' $TMP)

                # last updated
                lastup=$(sed -n 's/"last_updated":"\(.*\)T\(.*\)Z"$/\1 \2/p' $TMP)

                # last updated by
                lastby=$(sed -n 's/"last_updater_username":"\(.*\)"$/\1/p' $TMP)

                echo "| [$i](https://hub.docker.com/r/uvarc/$i) | $j | \`$base\` | $size | $lastup | \`$lastby\` |"
            fi
        done
        cd ..
    fi
done >>$README

cat >>$README <<EOF

Note:
- App link redirects to Docker Hub repository.
- The \`*.sif\` Singularity image size (created after \`singularity pull\`) is about the same as the compressed size.

EOF

rm $TMP
