FROM ubuntu:20.04
ARG ARCH=32
RUN dpkg --add-architecture i386 

RUN apt-get update && apt-get install -y --no-install-recommends \
        wget software-properties-common gpg-agent dirmngr && \
    rm -rf /var/lib/apt/lists/*

RUN wget -nc https://dl.winehq.org/wine-builds/winehq.key && \
    mv winehq.key /usr/share/keyrings/winehq-archive.key

RUN wget -nc https://dl.winehq.org/wine-builds/ubuntu/dists/focal/winehq-focal.sources && \
    mv winehq-focal.sources /etc/apt/sources.list.d/

#RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 76F1A20FF987672F

RUN apt-get update && apt-get install -y --install-recommends \
        winehq-stable winbind && \
    rm -rf /var/lib/apt/lists/*

RUN wget --no-check-certificate \
        https://github.com/WarrenPinnacle/SLAMM6.7/blob/master/EXE/${ARCH}-bit/slamm6.exe \
        https://github.com/WarrenPinnacle/SLAMM6.7/blob/master/EXE/${ARCH}-bit/SLAMM6.INI \
        https://raw.githubusercontent.com/WarrenPinnacle/SLAMM6.7/master/EXE/SLAMM_License.txt

ENV WINEDEBUG=fixme-all \
    WINEARCH=win${ARCH}

RUN wget https://dl.winehq.org/wine/wine-mono/7.0.0/wine-mono-7.0.0-x86.msi && \
    wineboot -u && \
    msiexec /i wine-mono-7.0.0-x86.msi /q && \
    rm wine-mono-7.0.0-x86.msi

ENTRYPOINT ["wine${ARCH}", "start", "/unix", "slamm6.exe"]
