ARG VERSION=2.2a2

FROM ubuntu:18.04 AS build
ARG VERSION
RUN apt-get update && apt-get install -y --no-install-recommends \
        wget ca-certificates \
        libxkbcommon-dev libxcb1-dev libgtk-3-dev \
        libglib2.0-dev mesa-common-dev libglu1-mesa-dev \
        build-essential qt5-default qt5-qmake libqt5opengl5-dev && \
    rm -rf /var/lib/apt/lists/*

RUN wget -q https://github.com/grahamrow/Muview2/archive/${VERSION}.tar.gz && \
    tar xf ${VERSION}.tar.gz && \
    cd Muview2-${VERSION} && \
    deploy/deployLinux.sh && \
    cd .. && rm ${VERSION}.tar.gz

FROM ubuntu:18.04
ARG VERSION
COPY --from=build /Muview2-$VERSION /Muview2-$VERSION

COPY --from=build \
    /lib/x86_64-linux-gnu/libbsd.so.0 \
    /lib/x86_64-linux-gnu/libc.so.6 \
    /lib/x86_64-linux-gnu/libdl.so.2 \
    /lib/x86_64-linux-gnu/libgcc_s.so.1 \
    /lib/x86_64-linux-gnu/libm.so.6 \
    /lib/x86_64-linux-gnu/libpcre.so.3 \
    /lib/x86_64-linux-gnu/libpthread.so.0 \
    /lib/x86_64-linux-gnu/librt.so.1 \
    /lib/x86_64-linux-gnu/libz.so.1 \
    /lib/x86_64-linux-gnu/

COPY --from=build /lib64/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2
COPY --from=build /usr/lib/x86_64-linux-gnu/qt5 /usr/lib/x86_64-linux-gnu/qt5

COPY --from=build \
    /usr/lib/x86_64-linux-gnu/libGL.so.1 \
    /usr/lib/x86_64-linux-gnu/libGLX.so.0 \
    /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 \
    /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 \
    /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 \
    /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5 \
    /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 \
    /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5 \
    /usr/lib/x86_64-linux-gnu/libX11.so.6 \
    /usr/lib/x86_64-linux-gnu/libXau.so.6 \
    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 \
    /usr/lib/x86_64-linux-gnu/libdouble-conversion.so.1 \
    /usr/lib/x86_64-linux-gnu/libfreetype.so.6 \
    /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 \
    /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 \
    /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 \
    /usr/lib/x86_64-linux-gnu/libicudata.so.60 \
    /usr/lib/x86_64-linux-gnu/libicui18n.so.60 \
    /usr/lib/x86_64-linux-gnu/libicuuc.so.60 \
    /usr/lib/x86_64-linux-gnu/libpng16.so.16 \
    /usr/lib/x86_64-linux-gnu/libstdc++.so.6 \
    /usr/lib/x86_64-linux-gnu/libxcb.so.1 \
    /usr/lib/x86_64-linux-gnu/

ENV PATH /Muview2-$VERSION:$PATH
ENV QT_QPA_PLATFORM_PLUGIN_PATH /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms

LABEL maintainer=rs7wz@virginia.edu

ENTRYPOINT ["muview"]
