FROM python:3.7.4-slim-buster AS py
ARG VERSION=1.6.0

# CUDA 10.2
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir \
        torch==$VERSION torchvision==0.7.0

# Python version 3.7.3
FROM gcr.io/distroless/python3-debian10
COPY --from=py /usr/local/lib/python3.7/site-packages /site-packages

ENV PYTHONPATH=/site-packages
ENV LANG C.UTF-8

LABEL maintainer=rs7wz@virginia.edu

ENTRYPOINT ["/usr/bin/python"]
